# Bun configuration for Face Analysis Engine
[install]
# Faster installs
cache = true
exact = false
peer = true

[install.scopes]
# Trust popular packages for faster installs
"vite" = { trusted = true }
"vitest" = { trusted = true }
"esbuild" = { trusted = true }

[run]
# Use Bun runtime for better performance
bun = true

[test]
# Test configuration
preload = []
coverage = false